<?php

namespace Database\Factories;

use Illuminate\Database\Eloquent\Factories\Factory;
use Illuminate\Support\Str;

/**
 * @extends \Illuminate\Database\Eloquent\Factories\Factory<\App\Models\User>
 */
class UserFactory extends Factory
{
    /**
     * Define the model's default state.
     *
     * @return array<string, mixed>
     */
    public function definition(): array
    {
        /**
         * The user factory defines a default state for the user model.
         * The default state contains the following attributes:
         * - name: A random name generated by the faker library.
         * - email: A unique email address generated by the faker library.
         * - email_verified_at: The current timestamp.
         * - password: A hashed password.
         * - remember_token: A random string.
         *
         * The default state can be overridden by calling the factory's "state" method.
         * For example, to create an unverified user, you can call the "unverified" method:
         * $factory->unverified()->create();
         */
        return [
            'name' => $this->faker->name(),
            'email' => $this->faker->unique()->safeEmail(),
            'email_verified_at' => now(),
            'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', // password
            'remember_token' => Str::random(10),
        ];
    }

    /**
     * Indicate that the model's email address should be unverified.
     *
     * @return static
     */
    public function unverified(): static
    {
        return $this->state(function (array $attributes) {
            return [
                'email_verified_at' => null,
            ];
        });
    }
}